---
title: "About Myself"
---

### Academic and Professional Experience



2023 – 2024: Truckers and Turnover Project, University of Minnesota, Morris

It is a multi-year study conducted by a team of University of Minnesota Morris faculty and students, as well as faculty at other institutions, in cooperation with several motor carriers. Project researchers worked with data from study firms along with new data collected by the project to identify the factors that predict retention, productivity, crash risk, and other on-the-job outcomes for truckers.


2023 – 2024: Statistics Student Representative, University of Minnesota, Morris

Regularly participate in departmental meetings and contribute to the promotion of all aspects of the faculty’s standards and environment.


2023 – 2024: Teaching Assistant, University of Minnesota, Morris

Assist in three courses: Mathematical Statistics, Probability and Stochastic Processes, Statistical Methods. Grade assignments and provide feedback to the instructor; track learning progress and collect feedback on student learning outcomes.






